version: "3"
services:
  web:
    build: ./app
    ports:
      - 27017:27017
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
